//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean MenuButton
        {
            get
            {
                return SteamVR_Actions.default_MenuButton;
            }
        }
        
        public virtual SteamVR_Action_Single Trigger
        {
            get
            {
                return SteamVR_Actions.default_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Single Grip
        {
            get
            {
                return SteamVR_Actions.default_Grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerButton
        {
            get
            {
                return SteamVR_Actions.default_TriggerButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripButton
        {
            get
            {
                return SteamVR_Actions.default_GripButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean PrimaryButton
        {
            get
            {
                return SteamVR_Actions.default_PrimaryButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean SecondaryButton
        {
            get
            {
                return SteamVR_Actions.default_SecondaryButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean PrimaryTouch
        {
            get
            {
                return SteamVR_Actions.default_PrimaryTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean SecondaryTouch
        {
            get
            {
                return SteamVR_Actions.default_SecondaryTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Primary2DAxisClick
        {
            get
            {
                return SteamVR_Actions.default_Primary2DAxisClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean Primary2DAxisTouch
        {
            get
            {
                return SteamVR_Actions.default_Primary2DAxisTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Secondary2DAxisClick
        {
            get
            {
                return SteamVR_Actions.default_Secondary2DAxisClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean Secondary2DAxisTouch
        {
            get
            {
                return SteamVR_Actions.default_Secondary2DAxisTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Primary2DAxis
        {
            get
            {
                return SteamVR_Actions.default_Primary2DAxis;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Secondary2DAxis
        {
            get
            {
                return SteamVR_Actions.default_Secondary2DAxis;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
